name: Auto-Sync Upstream Spec

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar nuestro repositorio
        uses: actions/checkout@v4

      - name: Fetch CERNs website
        run: |
          # Chech in CERN's website if there is a new GEANT4 release
          LATEST_VERSION=$(curl -sL https://geant4.web.cern.ch/download/ | grep -oP "(?<=/download/)[0-9]+\.[0-9]+\.[0-9]+(?=\.html)")
          
          if [ -z "$LATEST_VERSION" ]; then
            echo "Error: Couldn't extract current version."
            exit 1
          fi
          echo "The latest version on web is: $LATEST_VERSION"
          
          if [ -f "version.txt" ]; then
            CURRENT_VERSION=$(cat version.txt)
          else
            CURRENT_VERSION="0.0.0"
          fi
          echo "Nuestra versión actual compilada es: $CURRENT_VERSION"
          
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "There is a newer release ($LATEST_VERSION)!"
            
            echo "$LATEST_VERSION" > version.txt
            
            curl -o geant4.spec https://raw.githubusercontent.com/Geant4/geant4/master/packaging/rpm/geant4.spec

            # Fix beta syntax && Disable HDF5 because it dont support Multithreading
            sed -i 's/%bcond hdf5 .*/%bcond_with hdf5/' geant4.spec
            sed -i 's/%bcond inventor .*/%bcond_with inventor/' geant4.spec
            # Fix dates
            sed -i 's/Fri June 7/Fri Jun 07/g' geant4.spec
            sed -i 's/Wed Dec 12/Tue Dec 12/g' geant4.spec
            # Fix qt version mismatch
            sed -i 's/-DGEANT4_USE_QT:BOOL=%{with qt5}/-DGEANT4_USE_QT:BOOL=%{with qt5} -DGEANT4_USE_QT_QT6:BOOL=OFF/g' geant4.spec
            
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add version.txt geant4.spec
            git commit -m "Upstream update to $LATEST_VERSION"
            git push
            
            echo "Pinging COPR..."
            curl -X POST "https://copr.fedorainfracloud.org/webhooks/custom/225596/c67cb9f3-feae-4acb-adf2-7d0f3e016985/geant4/"

            echo "Commited. Waiting for COPR..."
          else
            echo "Up to date"
          fi
